### ISSUE TITLE
documentation required in LinkML or MIxS: who wins when there is a conflict in a slot definition/usage between a `is_a` parent and a `mixin`?

### ISSUE THREAD

**Issue by turbomam** [GenomicsStandardsConsortium/mixs-missing-value-sandbox#4]
first: determine what slots are used by both `Checklist`s and `Extension`s

**Comment by turbomam** [comment]
may especially be of interest for `recommended` and `required`

**Comment by turbomam** [comment]
see [src/scripts/mims_and_soil_slots.py](https://github.com/GenomicsStandardsConsortium/mixs-missing-value-sandbox/blob/4-is-this-a-reasonable-place-for-determining-who-wins-when-there-is-a-conflict-in-a-slot-definitionusage-between-a-is_a-parent-and-a-mixin/src/scripts/mims_and_soil_slots.py)

I'm illustrating this with a slot called `conflicting`, which has conflicting `pattern`s

It looks like `Mims` (a `Checklist`, bound with `mixins`) wins over `Soil` (an `Extension`, bound with `is_a`) in `MimsSoil`

**So what if there are multiple `mixins`?**

```yaml
  MimsSoil:
    description: MIxS Data that comply with the Mims checklist and the Soil Extension
    title: Mims combined with Soil
    in_subset:
      - combination_classes
    is_a: Soil
    mixins:
      - Mims
    class_uri: MIXS:0010007_0016012
```

> conflicting slot's usage in Mims:
> name: conflicting
> pattern: ^[a-zA-Z]+$
> 
> conflicting slot's usage in Soil:
> name: conflicting
> pattern: ^[0-9]+$
> 
> Induced slot conflicting in MimsSoil
> 
> name: conflicting
> description: intentionally set to incompatible states between a Checklist and an Extension
> from_schema: https://w3id.org/GenomicsStandardsConsortium/mixs-missing-value-sandbox
> alias: conflicting
> owner: MimsSoil
> domain_of:
> - Mims
> - Soil
> 
> range: string
> pattern: ^[a-zA-Z]+$
